// Catechism question <-> confession paragraph links.
//
// The mappings are generated by scripts/draft-catechism-links.mjs and live in
// shared/data/catechism, synced here by npm run sync:confessions. This module
// is the only place that knows their shape; pages ask it questions.
//
// Two directions matter, and they want different indexes:
//   - a confession paragraph asking "which questions expound me?"  (byParagraph)
//   - a catechism asking "where does my question live?"             (rows)
//
// Adding a catechism means adding a row to PAIRS in the drafting script and one
// import below. Nothing else here is per-catechism.

import manifestJson from "../data/catechism/manifest.json";
import bcLbcf1689Json from "../data/catechism/bc-lbcf-1689.json";
import wscWestminsterJson from "../data/catechism/wsc-westminster-confession.json";
import wlcWestminsterJson from "../data/catechism/wlc-westminster-confession.json";

export type Confidence = "high" | "medium" | "low" | "none";

export type QuestionLink = {
  /** Paragraph reference, "11.1". */
  ref: string;
  /** Fraction of the question's proof texts the paragraph also cites, or null when routed via the spine. */
  coverage: number | null;
};

export type MappingRow = {
  /** Question slug on catechize.ing, "bc-36". */
  id: string;
  n: number;
  title: string;
  cohort: string;
  proofs: number;
  links: QuestionLink[];
  confidence: Confidence;
  decision: string;
  margin?: number;
  /** Questions whose proof texts were borrowed, where this question cites none. */
  proofsFrom?: string[];
  /** Where another confession carries what this one does not. */
  elsewhere?: {
    doc: string;
    short: string;
    refs: string[];
    coverage: number;
    /** Alignment spine row id recording the gap. */
    gap?: string;
  };
  rejected?: string[];
};

export type CatechismMeta = {
  prefix: string;
  label: string;
  short: string;
};

export type Mapping = {
  id: string;
  generatedAt: string;
  catechism: CatechismMeta;
  confession: { slug: string; title: string; unitLabel: string };
  rows: MappingRow[];
};

const mappings: Mapping[] = [
  bcLbcf1689Json as Mapping,
  wscWestminsterJson as Mapping,
  wlcWestminsterJson as Mapping,
];

const manifest = manifestJson as {
  generatedAt: string;
  mappings: { id: string; questions: number; linked: number; paragraphs: number }[];
};

const byId = new Map(mappings.map((mapping) => [mapping.id, mapping]));

/** A question as it appears against one paragraph. */
export type ParagraphQuestion = {
  id: string;
  n: number;
  title: string;
  catechism: CatechismMeta;
  confidence: Confidence;
  coverage: number | null;
  decision: string;
  /** True when this paragraph is the question's second reading, not its first. */
  secondary: boolean;
  href: string;
};

/** Every question that maps to a paragraph, keyed "<confession slug>|<ref>". */
const byParagraph = new Map<string, ParagraphQuestion[]>();

for (const mapping of mappings) {
  for (const row of mapping.rows) {
    row.links.forEach((link, index) => {
      const key = `${mapping.confession.slug}|${link.ref}`;
      const list = byParagraph.get(key) ?? [];
      list.push({
        id: row.id,
        n: row.n,
        title: row.title,
        catechism: mapping.catechism,
        confidence: row.confidence,
        coverage: link.coverage,
        decision: row.decision,
        secondary: index > 0,
        href: questionUrl(row.id),
      });
      byParagraph.set(key, list);
    });
  }
}

const CONFIDENCE_ORDER: Record<Confidence, number> = { high: 0, medium: 1, low: 2, none: 3 };

// Display order for catechisms, used only to break ties between links of equal
// strength. Anything not listed sorts after, alphabetically.
const CATECHISM_ORDER = ["bc", "wsc", "wlc", "hc", "aoc", "gc"];

const catechismRank = (prefix: string) => {
  const index = CATECHISM_ORDER.indexOf(prefix);
  return index === -1 ? CATECHISM_ORDER.length : index;
};

for (const list of byParagraph.values()) {
  // Ordered by how strongly the link is held, so the first thing a reader sees
  // under a paragraph is the question most clearly about it:
  //
  //   1. confidence      — a confident link outranks a suggested one
  //   2. primary first   — a question's own paragraph before its second reading
  //   3. coverage        — more of the question's proof texts landing here
  //   4. catechism, then question number, so equal links stay in a stable,
  //      predictable order rather than shuffling between paragraphs
  //
  // Everything past the first few is collapsed in the UI, so this ordering is
  // what decides which links a reader actually sees.
  list.sort(
    (a, b) =>
      CONFIDENCE_ORDER[a.confidence] - CONFIDENCE_ORDER[b.confidence] ||
      Number(a.secondary) - Number(b.secondary) ||
      (b.coverage ?? 0) - (a.coverage ?? 0) ||
      catechismRank(a.catechism.prefix) - catechismRank(b.catechism.prefix) ||
      a.catechism.short.localeCompare(b.catechism.short) ||
      a.n - b.n
  );
}

export function questionUrl(slug: string): string {
  // /q/<slug> exists but 301s here; link to the destination directly.
  return `https://catechize.ing/questions/${slug}`;
}

export function listMappings(): Mapping[] {
  return mappings;
}

export function getMapping(id: string): Mapping | undefined {
  return byId.get(id);
}

export function mappingStats(id: string) {
  return manifest.mappings.find((entry) => entry.id === id);
}

/** Questions expounding one confession paragraph, strongest first. */
export function questionsForParagraph(
  confessionSlug: string,
  unitNumber: number,
  paragraphNumber: number
): ParagraphQuestion[] {
  return byParagraph.get(`${confessionSlug}|${unitNumber}.${paragraphNumber}`) ?? [];
}

/** Whether any catechism maps into this confession at all. */
export function hasCatechismLinks(confessionSlug: string): boolean {
  return mappings.some((mapping) => mapping.confession.slug === confessionSlug);
}

/** Catechisms mapped into a confession, for a page heading. */
export function catechismsFor(confessionSlug: string): CatechismMeta[] {
  return mappings
    .filter((mapping) => mapping.confession.slug === confessionSlug)
    .map((mapping) => mapping.catechism);
}

/** Rows grouped by the chapter they land in, for the per-mapping page. */
export function rowsByChapter(mapping: Mapping) {
  const groups = new Map<number, MappingRow[]>();
  const unplaced: MappingRow[] = [];

  for (const row of mapping.rows) {
    if (!row.links.length) {
      unplaced.push(row);
      continue;
    }
    const chapter = Number(row.links[0].ref.split(".")[0]);
    const list = groups.get(chapter) ?? [];
    list.push(row);
    groups.set(chapter, list);
  }

  return {
    chapters: [...groups.entries()]
      .sort((a, b) => a[0] - b[0])
      .map(([chapter, rows]) => ({ chapter, rows })),
    unplaced,
  };
}
